name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # Se dispara cada vez que subes cambios a la rama main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          # Si tu index.html está en la raíz, deja '.'
          # Si está en una carpeta, cambia '.' por el nombre de la carpeta
          path: '.' 

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
